# Generated by Django 4.2.4 on 2023-08-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_authapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="castomuser",
            name="count_following",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
