# Generated by Django 4.2.4 on 2023-08-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users_books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=50)),
                ("author_name", models.CharField(max_length=50)),
                ("year_of_writing", models.PositiveIntegerField()),
                ("total_page", models.IntegerField()),
                ("description", models.TextField()),
                ("book_image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
