# Generated by Django 4.2.4 on 2023-08-23 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainapp", "0002_alter_users_books_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users_books",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_images", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
