# Generated by Django 4.2.4 on 2023-08-24 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0003_alter_users_books_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users_books",
            name="current_page",
        ),
    ]
